// angular/src/app/admin/shared/feature-tree.component.ts
import { Component, Injector, inject } from '@angular/core';
import { FeatureTreeEditModel } from '@app/admin/shared/feature-tree-edit.model';
import { AppComponentBase } from '@shared/common/app-component-base';
import { FlatFeatureDto, NameValueDto } from '@shared/service-proxies/service-proxies';
import { ArrayToTreeConverterService } from '@shared/utils/array-to-tree-converter.service';
import { TreeDataHelperService } from '@shared/utils/tree-data-helper.service';
import { TreeNode, PrimeTemplate } from 'primeng/api';
import { find as _find, forEach as _forEach, filter as _filter, remove as _remove } from 'lodash-es';
import { TreeModule } from 'primeng/tree';

import { FormsModule } from '@angular/forms';

@Component({
    selector: 'feature-tree',
    templateUrl: './feature-tree.component.html',
    styleUrls: ['./feature-tree.component.less'],
    imports: [TreeModule, FormsModule],
})
export class FeatureTreeComponent extends AppComponentBase {
    private _arrayToTreeConverterService = inject(ArrayToTreeConverterService);
    private _treeDataHelperService = inject(TreeDataHelperService);

    _editData: FeatureTreeEditModel;
    treeData: any;
    selectedFeatures: TreeNode[] = [];

    constructor(...args: unknown[]);

    constructor() {
        const injector = inject(Injector);

        super(injector);
    }

    set editData(val: FeatureTreeEditModel) {
        this._editData = val;
        this.setTreeData(val.features);
        this.setSelectedNodes(val);
    }

    setTreeData(permissions: FlatFeatureDto[]) {
        this.treeData = this._arrayToTreeConverterService.createTree(
            permissions,
            'parentName',
            'name',
            null,
            'children',
            [
                {
                    target: 'key',
                    source: 'name',
                },
                {
                    target: 'label',
                    source: 'displayName',
                },
                {
                    target: 'expandedIcon',
                    value: 'fa fa-folder-open text-warning',
                },
                {
                    target: 'collapsedIcon',
                    value: 'fa fa-folder text-warning',
                },
                {
                    target: 'expanded',
                    value: true,
                },
                {
                    target: 'selectable',
                    targetFunction(item) {
                        return item.inputType.name === 'CHECKBOX';
                    },
                },
            ]
        );
    }

    setSelectedNodes(val: FeatureTreeEditModel) {
        this.selectedFeatures = [];
        _forEach(val.features, (feature) => {
            let items = _filter(val.featureValues, { name: feature.name });
            if (items && items.length === 1) {
                let item = items[0];
                this.setSelectedNode(item.name, item.value);
            } else {
                this.setSelectedNode(feature.name, feature.defaultValue);
            }
        });
    }

    setSelectedNode(featureName, value) {
        let node;

        const normalizedValue = value.trim().toLowerCase();

        if (normalizedValue === 'true') {
            node = this._treeDataHelperService.findNode(this.treeData, { data: { name: featureName } });
            this.selectedFeatures.push(node);
        } else if (value && normalizedValue !== 'false') {
            node = this._treeDataHelperService.findNode(this.treeData, { data: { name: featureName } });
            node.value = value;
            this.selectedFeatures.push(node);
        }
    }

    getGrantedFeatures(): NameValueDto[] {
        if (!this._editData.features) {
            return [];
        }

        let features: NameValueDto[] = [];

        for (let i = 0; i < this._editData.features.length; i++) {
            let feature = new NameValueDto();
            feature.name = this._editData.features[i].name;
            feature.value = this.getFeatureValueByName(feature.name);

            features.push(feature);
        }

        return features;
    }

    onDropdownChange(node) {
        if (node.value) {
            node.selected = true;
        }
    }

    onInputChange(node) {
        if (node.value) {
            node.selected = true;
        }
    }

    findFeatureByName(featureName: string): FlatFeatureDto {
        const self = this;

        const feature = _find(self._editData.features, (f) => f.name === featureName);

        if (!feature) {
            abp.log.warn('Could not find a feature by name: ' + featureName);
        }

        return feature;
    }

    findFeatureValueByName(featureName: string) {
        const self = this;
        const feature = self.findFeatureByName(featureName);
        if (!feature) {
            return '';
        }

        const featureValue = _find(self._editData.featureValues, (f) => f.name === featureName);
        if (!featureValue) {
            return feature.defaultValue;
        }

        return featureValue.value;
    }

    isFeatureValueValid(featureName: string, value: string): boolean {
        const self = this;
        const feature = self.findFeatureByName(featureName);
        if (!feature || !feature.inputType || !feature.inputType.validator) {
            return true;
        }

        const validator = feature.inputType.validator as any;
        if (validator.name === 'STRING') {
            if (value === undefined || value === null) {
                return validator.attributes.AllowNull;
            }

            if (typeof value !== 'string') {
                return false;
            }

            if (validator.attributes.MinLength > 0 && value.length < validator.attributes.MinLength) {
                return false;
            }

            if (validator.attributes.MaxLength > 0 && value.length > validator.attributes.MaxLength) {
                return false;
            }

            if (validator.attributes.RegularExpression) {
                return new RegExp(validator.attributes.RegularExpression).test(value);
            }
        } else if (validator.name === 'NUMERIC') {
            const numValue = parseInt(value);

            if (isNaN(numValue)) {
                return false;
            }

            const minValue = validator.attributes.MinValue;
            if (minValue > numValue) {
                return false;
            }

            const maxValue = validator.attributes.MaxValue;
            if (maxValue > 0 && numValue > maxValue) {
                return false;
            }
        }

        return true;
    }

    areAllValuesValid(): boolean {
        let result = true;

        _forEach(this._editData.features, (feature) => {
            let value = this.getFeatureValueByName(feature.name);
            if (!this.isFeatureValueValid(feature.name, value)) {
                result = false;
            }
        });

        return result;
    }

    setFeatureValueByName(featureName: string, value: string): void {
        const featureValue = _find(this._editData.featureValues, (f) => f.name === featureName);
        if (!featureValue) {
            return;
        }

        featureValue.value = value;
    }

    isFeatureSelected(name: string): boolean {
        let nodes = _filter(this.selectedFeatures, { data: { name: name } });
        return nodes && nodes.length === 1;
    }

    getFeatureValueByName(featureName: string): string {
        let feature = this._treeDataHelperService.findNode(this.treeData, { data: { name: featureName } });
        if (!feature) {
            return null;
        }

        if (feature.value) {
            return feature.value;
        }

        if (!this.isFeatureSelected(featureName)) {
            return 'false';
        }

        return 'true';
    }

    isFeatureEnabled(featureName: string): boolean {
        const self = this;
        const value = self.findFeatureValueByName(featureName);
        return value.toLowerCase() === 'true';
    }

    nodeSelect(event) {
        let parentNode = this._treeDataHelperService.findParent(this.treeData, {
            data: { name: event.node.data.name },
        });

        while (parentNode != null) {
            const isParentNodeAdded = _find(this.selectedFeatures, (f) => f.data.name === parentNode.data.name);
            if (!isParentNodeAdded) {
                this.selectedFeatures.push(parentNode);
            }

            parentNode = this._treeDataHelperService.findParent(this.treeData, {
                data: { name: parentNode.data.name },
            });
        }
    }

    onNodeUnselect(event) {
        let childrenNodes = this._treeDataHelperService.findChildren(this.treeData, {
            data: { name: event.node.data.name },
        });
        childrenNodes.push(event.node.data.name);
        _remove(this.selectedFeatures, (x) => childrenNodes.indexOf(x.data.name) !== -1);
    }
}

// react/src/pages/admin/components/common/trees/FeatureTree.tsx
import {
  useState,
  useEffect,
  useImperativeHandle,
  forwardRef,
  type Key,
} from "react";
import { Tree } from "antd";
import type { CheckInfo } from "@rc-component/tree/lib/Tree";
import { FlatFeatureDto, NameValueDto } from "@api/generated/service-proxies";
import {
  arrayToTree,
  getAllChildrenKeys,
  type AppDataNode,
} from "../../../../../lib/tree-helper";

interface FeatureTreeProps {
  editData?: FeatureTreeEditModel;
}

interface FeatureTreeEditModel {
  features: FlatFeatureDto[];

  featureValues: NameValueDto[];
}

export interface FeatureTreeRef {
  getGrantedFeatures: () => NameValueDto[];
  areAllValuesValid: () => boolean;
}

const FeatureTree = forwardRef<FeatureTreeRef, FeatureTreeProps>(
  ({ editData }, ref) => {
    const [treeData, setTreeData] = useState<AppDataNode<FlatFeatureDto>[]>([]);
    const [checkedKeys, setCheckedKeys] = useState<string[]>([]);
    const [inputValues, setInputValues] = useState<{ [key: string]: string }>(
      {},
    );

    useEffect(() => {
      if (!editData?.features) {
        return;
      }

      const tree = arrayToTree(
        editData.features as Array<FlatFeatureDto & Record<string, unknown>>,
        "parentName",
        "name",
      );
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setTreeData(tree);

      const initialCheckedKeys: string[] = [];
      const initialInputValues: { [key: string]: string } = {};

      editData.features.forEach((feature) => {
        const featureValue = editData.featureValues.find(
          (f) => f.name === feature.name,
        );
        const value = featureValue ? featureValue.value : feature.defaultValue;

        if (feature.inputType?.name === "CHECKBOX") {
          if (value?.toLowerCase() === "true") {
            initialCheckedKeys.push(feature.name!);
          }
        } else if (value) {
          initialInputValues[feature.name!] = value;
        }
      });

      setCheckedKeys(initialCheckedKeys);
      setInputValues(initialInputValues);
    }, [editData]);

    const isFeatureValueValid = (
      feature: FlatFeatureDto,
      value: string,
    ): boolean => {
      const validator = feature.inputType?.validator;
      if (!validator) return true;

      if (validator.name === "STRING") {
        if (value === undefined || value === null) {
          return !!validator.attributes?.AllowNull;
        }
        if (typeof value !== "string") return false;
        const min = validator.attributes?.MinLength ?? 0;
        const max = validator.attributes?.MaxLength ?? 0;
        if (min > 0 && value.length < min) return false;
        if (max > 0 && value.length > max) return false;
        const regex = validator.attributes?.RegularExpression;
        if (regex) {
          try {
            return new RegExp(regex).test(value);
          } catch {
            return false;
          }
        }
        return true;
      }

      if (validator.name === "NUMERIC") {
        const num = parseInt(value, 10);
        if (isNaN(num)) return false;
        const min = validator.attributes?.MinValue ?? Number.MIN_SAFE_INTEGER;
        const max = validator.attributes?.MaxValue ?? 0;
        if (num < min) return false;
        if (max > 0 && num > max) return false;
        return true;
      }
      return true;
    };

    useImperativeHandle(ref, () => ({
      getGrantedFeatures: () => {
        if (!editData?.features) return [];

        return editData.features.map((feature) => {
          let value = "false";
          if (feature.inputType?.name === "CHECKBOX") {
            value = checkedKeys.includes(feature.name!) ? "true" : "false";
          } else if (inputValues[feature.name!]) {
            value = inputValues[feature.name!];
          }
          return new NameValueDto({ name: feature.name, value: value });
        });
      },
      areAllValuesValid: () => {
        if (!editData?.features) return true;
        for (const feature of editData.features) {
          const fName = feature.name as string;
          let value: string;
          if (feature.inputType?.name === "CHECKBOX") {
            value = checkedKeys.includes(fName) ? "true" : "false";
          } else if (inputValues[fName]) {
            value = inputValues[fName];
          } else {
            value = feature.defaultValue || "";
          }
          if (!isFeatureValueValid(feature, value)) return false;
        }
        return true;
      },
    }));

    const onCheck = (
      checked: { checked: Key[]; halfChecked: Key[] } | Key[],
      info: CheckInfo<AppDataNode<FlatFeatureDto>>,
    ) => {
      const checkedArray = Array.isArray(checked) ? checked : checked.checked;
      let newCheckedKeys = checkedArray.map((key) => String(key));

      if (info.checked) {
        let parent = info.node.parent;
        while (parent) {
          const parentKey = String(parent.key);
          if (!newCheckedKeys.includes(parentKey)) {
            newCheckedKeys.push(parentKey);
          }
          parent = parent.parent;
        }
      } else {
        const childrenKeys = getAllChildrenKeys(info.node);
        newCheckedKeys = newCheckedKeys.filter(
          (key) => !childrenKeys.includes(key),
        );
      }
      setCheckedKeys(newCheckedKeys);
    };

    const handleInputChange = (name: string, value: string) => {
      setInputValues((prev) => ({ ...prev, [name]: value }));
    };

    const renderTitle = (node: AppDataNode<FlatFeatureDto>) => {
      const inputTypeName = node.data?.inputType?.name ?? "";
      const featureName = node.data?.name ?? "";

      return (
        <span className="d-flex align-items-center gap-2">
          <span>
            {typeof node.title === "function" ? node.title(node) : node.title}
          </span>
          {inputTypeName === "SINGLE_LINE_STRING" && (
            <input
              className="form-control form-control-sm"
              style={{ width: "100px" }}
              value={inputValues[featureName]}
              onChange={(e) => handleInputChange(featureName, e.target.value)}
              onClick={(e) => e.stopPropagation()}
            />
          )}
          {inputTypeName === "COMBOBOX" && (
            <select
              className="form-control"
              style={{ width: "150px" }}
              value={inputValues[featureName]}
              onChange={(e) =>
                handleInputChange(
                  featureName,
                  (e.target as HTMLSelectElement).value,
                )
              }
              onClick={(e) => e.stopPropagation()}
            >
              <option value=""></option>
              {node.data.inputType?.itemSource?.items?.map(
                (item: { value?: string | number; displayText?: string }) => (
                  <option key={String(item.value)} value={String(item.value)}>
                    {item.displayText}
                  </option>
                ),
              )}
            </select>
          )}
        </span>
      );
    };

    return (
      <Tree
        checkable
        selectable={false}
        defaultExpandAll
        checkedKeys={checkedKeys}
        onCheck={onCheck}
        treeData={treeData}
        titleRender={renderTitle}
        showLine={true}
      />
    );
  },
);

export default FeatureTree;
