// react/src/pages/account/email-activation/confirm-email.tsx
import React, { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import {
  AccountServiceProxy,
  ActivateEmailInput,
  ResolveTenantIdInput,
} from "@api/generated/service-proxies";
import { useServiceProxy } from "@/api/service-proxy-factory";
import L from "@/lib/L";
import { useSession } from "@/hooks/useSession";

const ConfirmEmailPage: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const accountService = useServiceProxy(AccountServiceProxy, []);
  const { user } = useSession();
  const cParam = searchParams.get("c") || undefined;
  const [waitMessage, setWaitMessage] = useState<string>("");

  const userIsAuthenticated = useMemo(() => {
    try {
      return !!user?.id;
    } catch {
      return false;
    }
  }, [user?.id]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setWaitMessage(L("PleaseWaitToConfirmYourEmailMessage"));

    const run = async () => {
      try {
        const tenantId = await accountService.resolveTenantId(
          new ResolveTenantIdInput({ c: cParam }),
        );
        const currentTenantId = abp?.multiTenancy?.getTenantIdCookie?.();
        if ((tenantId || null) !== (currentTenantId || null)) {
          abp?.multiTenancy?.setTenantIdCookie?.(tenantId || undefined);
        }

        const input = new ActivateEmailInput();
        input.c = cParam;
        await accountService.activateEmail(input);

        abp?.notify?.success?.(L("YourEmailIsConfirmedMessage"), "", {
          willClose: () => {
            if (userIsAuthenticated) {
              abp?.utils?.deleteCookie?.("Abp.AuthToken", abp?.appPath);
              navigate("/account/login", { replace: true });
            } else {
              navigate("/account/login", { replace: true });
            }
          },
        });
      } catch {
        navigate("/account/login", { replace: true });
      }
    };

    run();
  }, [accountService, cParam, navigate, userIsAuthenticated]);

  return (
    <div className="login-form">
      <div className="alert alert-success text-center" role="alert">
        <div className="alert-text">{waitMessage}</div>
      </div>
    </div>
  );
};

export default ConfirmEmailPage;

// angular/src/account/email-activation/confirm-email.component.ts
import { Component, Injector, OnInit, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AppAuthService } from '@app/shared/common/auth/app-auth.service';
import { AppComponentBase } from '@shared/common/app-component-base';
import { AccountServiceProxy, ActivateEmailInput, ResolveTenantIdInput } from '@shared/service-proxies/service-proxies';

@Component({
    template: `
        <div class="login-form">
            <div class="alert alert-success text-center" role="alert">
                <div class="alert-text">{{ waitMessage }}</div>
            </div>
        </div>
    `,
})
export class ConfirmEmailComponent extends AppComponentBase implements OnInit {
    private _accountService = inject(AccountServiceProxy);
    private _router = inject(Router);
    private _activatedRoute = inject(ActivatedRoute);
    private _appAuthService = inject(AppAuthService);

    waitMessage: string;

    model: ActivateEmailInput = new ActivateEmailInput();

    constructor(...args: unknown[]);

    constructor() {
        const injector = inject(Injector);

        super(injector);
    }

    ngOnInit(): void {
        this.waitMessage = this.l('PleaseWaitToConfirmYourEmailMessage');
        this.model.c = this._activatedRoute.snapshot.queryParams['c'];

        this._accountService.resolveTenantId(new ResolveTenantIdInput({ c: this.model.c })).subscribe((tenantId) => {
            if (this.appSession.user && this.appSession.tenantId !== tenantId) {
                this._appAuthService.logout(true, window.location.href);
                return;
            }

            abp.multiTenancy.setTenantIdCookie(tenantId);

            this._accountService.activateEmail(this.model).subscribe(() => {
                this.notify.success(this.l('YourEmailIsConfirmedMessage'), '', {
                    willClose: () => {
                        this._router.navigate(['account/login']);
                    },
                });
            });
        });
    }

    parseTenantId(tenantIdAsStr?: string): number {
        let tenantId = !tenantIdAsStr ? undefined : parseInt(tenantIdAsStr, 10);
        if (Number.isNaN(tenantId)) {
            tenantId = undefined;
        }

        return tenantId;
    }
}
