// react/src/pages/account/login/index.tsx
import React, { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import {
  AuthenticateModel,
  SessionServiceProxy,
  UpdateUserSignInTokenOutput,
  ExternalLoginProviderInfoModel,
} from "@api/generated/service-proxies";
import { useLoginService } from "./login.service";
import { useServiceProxy } from "@/api/service-proxy-factory";
import L from "@/lib/L";
import recaptcha from "@/lib/recaptcha-v3";
import {
  getProviderIcon,
  getProviderDisplayName,
} from "@/lib/external-login-provider";

type LoginFormValues = {
  userNameOrEmailAddress: string;
  password: string;
  rememberMe: boolean;
};

const LoginPage: React.FC = () => {
  const sessionService = useServiceProxy(SessionServiceProxy, []);

  const {
    initExternalLoginProviders,
    externalLoginProviders,
    authenticate,
    handleExternalCallbackIfAny,
    startExternalLogin,
    isPasswordlessLoginEnabled,
    isSelfRegistrationAllowed,
    isTenantSelfRegistrationAllowed,
    isMultiTenancyEnabled,
    multiTenancySideIsTenant,
  } = useLoginService();

  const {
    register,
    handleSubmit,
    formState: { isValid },
  } = useForm<LoginFormValues>({
    mode: "onChange",
    defaultValues: {
      userNameOrEmailAddress: "",
      password: "",
      rememberMe: false,
    },
  });

  const [submitting, setSubmitting] = useState(false);
  const [extProvidersLoaded, setExtProvidersLoaded] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  useEffect(() => {
    const userId = abp?.session?.userId || 0;
    const returnUrl =
      new URLSearchParams(window.location.search).get("returnUrl") || "";
    const singleSignIn =
      new URLSearchParams(window.location.search).get("singleSignIn") ===
      "true";
    if (userId > 0 && returnUrl && singleSignIn) {
      sessionService
        .updateUserSignInToken()
        .then((result: UpdateUserSignInTokenOutput) => {
          const sep = returnUrl.includes("?") ? "&" : "?";
          const full = `${returnUrl}${sep}accessToken=${encodeURIComponent(result.signInToken || "")}&userId=${encodeURIComponent(result.encodedUserId || "")}&tenantId=${encodeURIComponent(result.encodedTenantId || "")}`;
          window.location.href = full;
        })
        .catch(() => {});
    }
  }, [sessionService]);

  useEffect(() => {
    initExternalLoginProviders()
      .then(() => setExtProvidersLoaded(true))
      .catch(() => setExtProvidersLoaded(true));
    handleExternalCallbackIfAny();
  }, [handleExternalCallbackIfAny, initExternalLoginProviders]);

  useEffect(() => {
    recaptcha.setCaptchaVisibilityOnLogin();
  }, []);

  const onSubmit = useCallback(
    async (values: LoginFormValues) => {
      setSubmitting(true);
      try {
        const model = new AuthenticateModel();
        model.userNameOrEmailAddress = values.userNameOrEmailAddress;
        model.password = values.password;
        model.rememberClient = values.rememberMe;
        await authenticate(model);
      } finally {
        setSubmitting(false);
      }
    },
    [authenticate],
  );

  const exts = (
    extProvidersLoaded ? externalLoginProviders : []
  ) as ExternalLoginProviderInfoModel[];

  return (
    <>
      <div className="login-form">
        <div className="pb-13 pt-lg-0 pt-5">
          <h3 className="fw-bolder text-gray-900 fs-h4 fs-h1-lg">
            {L("LogIn")}
          </h3>
        </div>

        <form className="login-form form" onSubmit={handleSubmit(onSubmit)}>
          <div className="mb-5">
            <input
              className="form-control form-control-solid h-auto py-7 px-6 rounded-lg fs-h6"
              type="text"
              placeholder={L("UserNameOrEmail")}
              autoComplete="username"
              {...register("userNameOrEmailAddress", { required: true })}
            />
          </div>

          <div className="mb-5" data-kt-password-meter="true">
            <div className="position-relative mb-3">
              <input
                className="form-control form-control-solid h-auto py-7 px-6 rounded-lg fs-h6"
                type={showPassword ? "text" : "password"}
                placeholder={L("Password")}
                autoComplete="current-password"
                maxLength={32}
                {...register("password", { required: true })}
              />
              <button
                type="button"
                aria-pressed={showPassword}
                aria-label={
                  showPassword ? L("HidePassword") : L("ShowPassword")
                }
                onClick={() => setShowPassword((s) => !s)}
                className="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
                style={{ transform: "translateY(-50%)" }}
              >
                <i
                  className={`fas ${showPassword ? "fa-eye" : "fa-eye-slash"} fs-4`}
                />
              </button>
            </div>
          </div>

          <div className="mb-5 d-flex justify-content-between mt-4">
            <label className="form-check form-check-custom form-check-solid">
              <input
                type="checkbox"
                className="form-check-input"
                {...register("rememberMe")}
              />
              <span className="form-check-label">{L("RememberMe")}</span>
            </label>
            <Link
              to="/account/forgot-password"
              className="text-primary fs-h6 fw-bolder text-hover-primary"
            >
              {L("ForgotPassword")}
            </Link>
          </div>

          <div className="pb-lg-0 pb-5">
            <button
              type="submit"
              disabled={!isValid || submitting}
              className="btn w-100 btn-primary fw-bolder fs-h6 px-8 py-4 my-3 me-3"
            >
              {L("LogIn")}
            </button>
          </div>
        </form>

        {(multiTenancySideIsTenant || !isMultiTenancyEnabled) &&
          exts.length > 0 && (
            <>
              <div className="mt-10 mb-2">
                <div className="divider">
                  <span>{L("LoginWith")}</span>
                </div>
              </div>
              <div className="pb-lg-0 pb-5 login__options">
                {exts.map((p) => (
                  <button
                    key={p.name}
                    className="btn btn-sm btn-light-primary fw-bolder py-2 mb-2 ml-0 me-2"
                    onClick={() => startExternalLogin(p)}
                    title={getProviderDisplayName(p.name || "")}
                  >
                    <i className={`fab fa-${getProviderIcon(p.name || "")}`} />{" "}
                    {getProviderDisplayName(p.name || "")}
                  </button>
                ))}
              </div>
            </>
          )}
      </div>

      <div className="mt-5">
        {isPasswordlessLoginEnabled && (
          <div className="mb-2">
            <span>{L("PasswordlessLogin_Description")}</span>{" "}
            <Link to="/account/passwordless-login" id="passwordless-btn">
              {L("ClickHere")}
            </Link>
          </div>
        )}

        {(isSelfRegistrationAllowed ||
          (!multiTenancySideIsTenant && isTenantSelfRegistrationAllowed)) && (
          <div className="mt-2">
            <span>{L("NotAMemberYet")}</span>
          </div>
        )}

        {multiTenancySideIsTenant && isSelfRegistrationAllowed && (
          <>
            <Link to="/account/register">{L("CreateAnAccount")}</Link>
            <span className="pipe-divider">|</span>
          </>
        )}

        {!multiTenancySideIsTenant && (
          <>
            <Link to="/account/select-edition">{L("NewTenant")}</Link>
            <span className="pipe-divider">|</span>
          </>
        )}

        <Link to="/account/email-activation" id="email-activation-btn">
          {L("EmailActivation")}
        </Link>
      </div>
    </>
  );
};

export default LoginPage;

// angular/src/account/login/login.component.ts
import { AbpSessionService } from 'abp-ng2-module';
import { AfterViewInit, Component, Injector, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { accountModuleAnimation } from '@shared/animations/routerTransition';
import { AppComponentBase } from '@shared/common/app-component-base';
import { SessionServiceProxy, UpdateUserSignInTokenOutput } from '@shared/service-proxies/service-proxies';
import { UrlHelper } from 'shared/helpers/UrlHelper';
import { ExternalLoginProvider, LoginService } from './login.service';
import { ReCaptchaV3WrapperService } from '@account/shared/recaptchav3-wrapper.service';
import { PasswordMeterComponent } from '@metronic/app/kt/components';
import { FormsModule } from '@angular/forms';
import { AutoFocusDirective } from '../../shared/utils/auto-focus.directive';

import { ValidationMessagesComponent } from '../../shared/utils/validation-messages.component';
import { LocalizePipe } from '@shared/common/pipes/localize.pipe';

@Component({
    templateUrl: './login.component.html',
    animations: [accountModuleAnimation()],
    styleUrls: ['./login.component.less'],
    imports: [FormsModule, AutoFocusDirective, ValidationMessagesComponent, RouterLink, LocalizePipe],
})
export class LoginComponent extends AppComponentBase implements OnInit, AfterViewInit {
    private _sessionService = inject(AbpSessionService);
    private _sessionAppService = inject(SessionServiceProxy);
    private _recaptchaWrapperService = inject(ReCaptchaV3WrapperService);

    loginService = inject(LoginService);

    submitting = false;
    isMultiTenancyEnabled: boolean = this.multiTenancy.isEnabled;
    capsLockOn = false;
    passwordFocused = false;

    constructor() {
        const injector = inject(Injector);

        super(injector);
    }

    get multiTenancySideIsTenant(): boolean {
        return this._sessionService.tenantId > 0;
    }

    get isTenantSelfRegistrationAllowed(): boolean {
        return this.setting.getBoolean('App.TenantManagement.AllowSelfRegistration');
    }

    get isSelfRegistrationAllowed(): boolean {
        if (!this._sessionService.tenantId) {
            return false;
        }

        return this.setting.getBoolean('App.UserManagement.AllowSelfRegistration');
    }

    get isPasswordlessLoginEnabled(): boolean {
        return (
            this.setting.getBoolean('App.UserManagement.PasswordlessLogin.IsEmailPasswordlessLoginEnabled') ||
            this.setting.getBoolean('App.UserManagement.PasswordlessLogin.IsSmsPasswordlessLoginEnabled')
        );
    }

    ngOnInit(): void {
        if (this._sessionService.userId > 0 && UrlHelper.getReturnUrl() && UrlHelper.getSingleSignIn()) {
            this._sessionAppService.updateUserSignInToken().subscribe((result: UpdateUserSignInTokenOutput) => {
                const initialReturnUrl = UrlHelper.getReturnUrl();
                const returnUrl =
                    initialReturnUrl +
                    (initialReturnUrl.indexOf('?') >= 0 ? '&' : '?') +
                    'accessToken=' +
                    result.signInToken +
                    '&userId=' +
                    result.encodedUserId +
                    '&tenantId=' +
                    result.encodedTenantId;

                location.href = returnUrl;
            });
        }

        PasswordMeterComponent.bootstrap();
        this.handleExternalLoginCallbacks();
    }

    ngAfterViewInit(): void {
        this._recaptchaWrapperService.setCaptchaVisibilityOnLogin();
    }

    handleExternalLoginCallbacks(): void {
        let state = UrlHelper.getQueryParametersUsingHash().state;
        let queryParameters = UrlHelper.getQueryParameters();

        if (state && state.indexOf('openIdConnect') >= 0) {
            this.loginService.openIdConnectLoginCallback({});
        }

        if (queryParameters.state && queryParameters.state.indexOf('openIdConnect') >= 0) {
            this.loginService.openIdConnectLoginCallback({});
        }

        if (queryParameters.twitter && queryParameters.twitter === '1') {
            let parameters = UrlHelper.getQueryParameters();
            let token = parameters['oauth_token'];
            let verifier = parameters['oauth_verifier'];
            this.loginService.twitterLoginCallback(token, verifier);
        }
    }

    login(): void {
        let recaptchaCallback = (token: string) => {
            this.showMainSpinner();

            this.submitting = true;
            this.loginService.authenticate(
                () => {
                    this.submitting = false;
                    this.hideMainSpinner();
                },
                null,
                token
            );
        };

        if (this._recaptchaWrapperService.useCaptchaOnLogin()) {
            this._recaptchaWrapperService
                .getService()
                .execute('login')
                .subscribe((token) => recaptchaCallback(token));
        } else {
            recaptchaCallback(null);
        }
    }

    externalLogin(provider: ExternalLoginProvider) {
        this.loginService.externalAuthenticate(provider);
    }

    checkCapsLock(event: KeyboardEvent) {
        this.capsLockOn = event.getModifierState?.('CapsLock') ?? false;
    }
}

<!--begin::Signin-->
<div class="login-form" [@routerTransition]>
    <div class="pb-13 pt-lg-0 pt-5">
        <h3 class="fw-bolder text-gray-900 fs-3 fs-lg-1">{{ 'LogIn' | localize }}</h3>
    </div>
    <!--begin::Form-->
    <form #loginForm="ngForm" class="login-form form" method="post" (ngSubmit)="login()">
        <div class="mb-5">
            <input
                #userNameOrEmailAddressInput="ngModel"
                [(ngModel)]="loginService.authenticateModel.userNameOrEmailAddress"
                autoFocus
                class="form-control form-control-solid h-auto py-7 px-6 rounded-lg fs-5"
                type="text"
                autocomplete="new-password"
                placeholder="{{ 'UserNameOrEmail' | localize }} *"
                name="userNameOrEmailAddress"
                required />
            @if (!userNameOrEmailAddressInput.touched) {
                <validation-messages [formCtrl]="userNameOrEmailAddressInput"></validation-messages>
            }
        </div>

        <div class="mb-5" data-kt-password-meter="true">
            <div class="position-relative mb-3">
                <input
                    #passwordInput="ngModel"
                    [(ngModel)]="loginService.authenticateModel.password"
                    class="form-control form-control-solid h-auto py-7 px-6 rounded-lg fs-5"
                    type="password"
                    autocomplete="new-password"
                    placeholder="{{ 'Password' | localize }} *"
                    name="password"
                    required
                    maxlength="32"
                    (keydown)="checkCapsLock($event)"
                    (keyup)="checkCapsLock($event)"
                    (focus)="passwordFocused = true"
                    (blur)="passwordFocused = false" />

                <div class="position-absolute top-50 end-0 translate-middle-y d-flex align-items-center gap-1 pe-3">
                    @if (capsLockOn && passwordFocused) {
                        <span
                            class="d-flex align-items-center justify-content-center"
                            style="width: 1.75rem; height: 1.75rem">
                            <i class="fas fa-arrow-up fs-5 text-muted"></i>
                        </span>
                    }
                    <!--begin::Visibility toggle-->
                    <span
                        class="d-flex align-items-center justify-content-center"
                        style="width: 1.75rem; height: 1.75rem; cursor: pointer"
                        data-kt-password-meter-control="visibility"
                        (mousedown)="$event.preventDefault()">
                        <i class="fas fa-eye-slash fs-5 text-muted">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                            <span class="path4"></span>
                        </i>
                        <i class="fas fa-eye d-none fs-5 text-muted">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                        </i>
                    </span>
                    <!--end::Visibility toggle-->
                </div>
            </div>
            @if (!passwordInput.touched) {
                <validation-messages [formCtrl]="passwordInput"></validation-messages>
            }
        </div>

        <div class="mb-5 d-flex justify-content-between mt-4">
            <label class="form-check form-check-custom form-check-solid">
                <input
                    type="checkbox"
                    name="rememberMe"
                    class="form-check-input"
                    value="true"
                    [(ngModel)]="loginService.rememberMe" />
                <span class="form-check-label">
                    {{ 'RememberMe' | localize }}
                </span>
            </label>
            <a
                routerLink="/account/forgot-password"
                id="forget-password"
                class="text-primary fs-5 fw-bolder text-hover-primary">
                {{ 'ForgotPassword' | localize }}
            </a>
        </div>

        <!--begin::Action-->
        <div class="pb-lg-0 pb-5">
            <button
                type="submit"
                [disabled]="!loginForm.form.valid"
                class="btn w-100 btn-primary fw-bolder fs-5 px-8 py-4 my-3 me-3">
                {{ 'LogIn' | localize }}
            </button>
        </div>

        <!--end::Action-->
    </form>

    <!--end::Form-->

    <!--begin::Options-->
    @if ((multiTenancySideIsTenant || !isMultiTenancyEnabled) && loginService.externalLoginProviders.length > 0) {
        <div class="mt-10 mb-2">
            <div class="divider">
                <span>{{ 'LoginWith' | localize }}</span>
            </div>
        </div>
    }

    @if ((multiTenancySideIsTenant || !isMultiTenancyEnabled) && loginService.externalLoginProviders.length > 0) {
        <div class="pb-lg-0 pb-5 login__options">
            @for (provider of loginService.externalLoginProviders; track provider) {
                <a
                    class="btn btn-sm btn-light-primary fw-bolder py-2 mb-2 ml-0 me-2"
                    (click)="externalLogin(provider)"
                    title="{{ provider.name }}">
                    <i class="fab fa-{{ provider.icon }}"></i>
                    {{ provider.name }}
                </a>
            }
        </div>
    }
    <!--end::Options-->
</div>

<div class="mt-5">
    @if (isPasswordlessLoginEnabled) {
        <div class="mb-2">
            <span>{{ 'PasswordlessLogin_Description' | localize }}</span>
            <a href="/account/passwordless-login" id="passwordless-btn">{{ 'ClickHere' | localize }}</a>
        </div>
    }

    @if (isSelfRegistrationAllowed || (!multiTenancySideIsTenant && isTenantSelfRegistrationAllowed)) {
        <div class="mt-2">
            <span>{{ 'NotAMemberYet' | localize }}</span>
        </div>
    }
    @if (isSelfRegistrationAllowed) {
        <span>
            <a routerLink="/account/register">{{ 'CreateAnAccount' | localize }}</a>
            <span class="pipe-divider">|</span>
        </span>
    }

    @if (!multiTenancySideIsTenant && isTenantSelfRegistrationAllowed) {
        <span>
            <a routerLink="/account/select-edition">{{ 'NewTenant' | localize }}</a>
            <span class="pipe-divider">|</span>
        </span>
    }

    <a routerLink="/account/email-activation" id="email-activation-btn">{{ 'EmailActivation' | localize }}</a>
</div>
